/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    audit: Audit;
    question: Question;
    law: Law;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
export interface Audit {
  id: string;
  date: string;
  dateCount: number;
  leadAuditorId: number;
  leadAuditeeId: number;
  status: string;
  place: string;
  topic: string;
  type: string;
  questions?: (string | Question)[] | null;
  updatedAt: string;
  createdAt: string;
}
export interface Question {
  id: string;
  audited: boolean;
  applicable: boolean;
  findingLevel: string;
  laws?: (string | Law)[] | null;
  updatedAt: string;
  createdAt: string;
}
export interface Law {
  id: string;
  law: string;
  type: string;
  text: string;
  description: string;
  validFrom: string;
  validUntil: string;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
